name: Sync Dev Notebooks
on: 
  push: 
    branches: [ dev ]
    
env:
  DATABRICKS_WORKSPACE_DEV: ${{ secrets.DATABRICKS_WORKSPACE_DEV }}
  DATABRICKS_TOKEN_DEV: ${{ secrets.DATABRICKS_TOKEN_DEV }}

jobs:
  Sync-Notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Submit Update Request
        run: sh ./.github/scripts/sync.sh 
