name: Sync Prod Notebooks
on: 
  push: 
    branches: [ master ]
    
env:
  DATABRICKS_WORKSPACE: ${{ secrets.DATABRICKS_WORKSPACE }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  Sync-Notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Submit Update Request
        run: sh ./.github/scripts/sync.sh 
